export const REPORT_KEYS = {
    GET_ALL_REPORTS: "GET_ALL_REPORTS",
    GET_REPORT: "GET_REPORT",
    CREATE_REPORT: "CREATE_REPORT",
    RESOLVE_REPORT: "RESOLVE_REPORT",
    GET_MY_REPORTS: "GET_MY_REPORTS",
    GET_PAGINATED_REPORTS: "GET_PAGINATED_REPORTS"
}